# Generated by Django 3.2.11 on 2022-10-20 13:32

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='id_employee',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='is_activated',
        ),
        migrations.AddField(
            model_name='advuser',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=3, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='advuser',
            name='change',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=3, verbose_name='Сдать'),
        ),
        migrations.AddField(
            model_name='advuser',
            name='chat_id',
            field=models.IntegerField(blank=True, help_text='Чтобы узнать свой chat_id, найдите @getmyid_bot в поиске телеграмма', null=True, verbose_name='Чат ID телеграмма'),
        ),
        migrations.AddField(
            model_name='advuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='advuser',
            name='premium',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=3, verbose_name='Премия'),
        ),
    ]
