# Generated by Django 3.2.11 on 2022-10-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20221020_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='chat_id',
            field=models.CharField(blank=True, help_text='Чтобы узнать свой chat_id, найдите @getmyid_bot в поиске телеграмма', max_length=9, null=True, verbose_name='Чат ID телеграмма'),
        ),
    ]
