# Generated by Django 3.2.11 on 2022-10-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_advuser_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='balance',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=1, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='change',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=1, verbose_name='Сдать'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='premium',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=1, verbose_name='Премия'),
        ),
    ]
