# Generated by Django 3.2.11 on 2022-10-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20221020_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='change',
            field=models.IntegerField(default=0, verbose_name='Сдать'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='premium',
            field=models.IntegerField(default=0, verbose_name='Премия'),
        ),
    ]
