# Generated by Django 3.2.11 on 2022-10-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20221021_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='change',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='premium',
        ),
    ]
