# Generated by Django 3.2.11 on 2022-10-20 15:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import ticketSystem.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=30, verbose_name='Город')),
                ('address', models.CharField(db_index=True, max_length=50, verbose_name='Адрес')),
                ('customer', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Клиент')),
                ('customer_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region=None)),
                ('description', models.TextField(db_index=True, verbose_name='Описание проблемы')),
                ('treaty', models.BooleanField(default=False, verbose_name='Отметить, если нужен договор')),
                ('ykp7', models.IntegerField(blank=True, default=0, null=True, verbose_name='УКП-7')),
                ('ykp12', models.IntegerField(blank=True, default=0, null=True, verbose_name='УКП-12')),
                ('rf', models.IntegerField(blank=True, default=0, null=True, verbose_name='RF')),
                ('tm', models.IntegerField(blank=True, default=0, null=True, verbose_name='TM')),
                ('md', models.IntegerField(blank=True, default=0, null=True, verbose_name='MD')),
                ('door_closer', models.IntegerField(blank=True, default=0, null=True, verbose_name='Доводчик')),
                ('img_door_closer', models.ImageField(blank=True, default='no_image.jpg', null=True, upload_to=ticketSystem.utilities.get_timestamp_path, verbose_name='Фото доводчика')),
                ('monetary', models.BooleanField(default=False, verbose_name='Денежная заявка')),
                ('price', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=1, null=True, verbose_name='Цена')),
                ('premium', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=1, null=True, verbose_name='Премия')),
                ('change', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=1, null=True, verbose_name='Сдать')),
                ('published', models.DateTimeField(db_index=True, default=datetime.datetime(2022, 10, 20, 18, 40, 29, 909345), verbose_name='Дата подачи заявки')),
                ('deadline', models.DateTimeField(default=datetime.datetime(2022, 10, 23, 18, 40, 29, 909345))),
                ('closing_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('status', models.CharField(choices=[('a', 'В работе'), ('b', 'Нужна сварка'), ('c', 'Выполнена')], default='a', max_length=20, verbose_name='Статус заявки')),
                ('handed_over', models.BooleanField(db_index=True, default=False, verbose_name='Деньги посчитаны')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-published'],
            },
        ),
    ]
