# Generated by Django 3.2.11 on 2022-10-20 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 20, 44, 15, 160399)),
        ),
        migrations.AlterField(
            model_name='applications',
            name='published',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 10, 20, 20, 44, 15, 160399), verbose_name='Дата подачи заявки'),
        ),
    ]
