# Generated by Django 3.2.11 on 2022-10-20 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSystem', '0002_auto_20221020_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='change',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Сдать'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 20, 47, 5, 355715)),
        ),
        migrations.AlterField(
            model_name='applications',
            name='premium',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Премия'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='published',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 10, 20, 20, 47, 5, 355715), verbose_name='Дата подачи заявки'),
        ),
    ]
