# Generated by Django 3.2.11 on 2022-10-20 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSystem', '0004_auto_20221021_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 24, 2, 7, 46, 526640)),
        ),
        migrations.AlterField(
            model_name='applications',
            name='published',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 10, 21, 2, 7, 46, 526640), verbose_name='Дата подачи заявки'),
        ),
    ]
