# Generated by Django 3.2.11 on 2022-10-21 10:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketSystem', '0005_auto_20221021_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 24, 13, 5, 25, 724222)),
        ),
        migrations.AlterField(
            model_name='applications',
            name='published',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 10, 21, 13, 5, 25, 724222), verbose_name='Дата подачи заявки'),
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(blank=True, default=0, null=True, verbose_name='Баланс')),
                ('premium', models.IntegerField(blank=True, default=0, null=True, verbose_name='Премия')),
                ('change', models.IntegerField(blank=True, default=0, null=True, verbose_name='Сдать')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
    ]
