# Generated by Django 3.2.11 on 2022-10-21 12:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketSystem', '0006_auto_20221021_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 24, 15, 54, 30, 913416)),
        ),
        migrations.AlterField(
            model_name='applications',
            name='published',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 10, 21, 15, 54, 30, 913416), verbose_name='Дата подачи заявки'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ykp7', models.FloatField(default=0, verbose_name='УКП-7')),
                ('ykp12', models.FloatField(default=0, verbose_name='УКП-12')),
                ('rf', models.FloatField(default=0, verbose_name='RF')),
                ('tm', models.FloatField(default=0, verbose_name='TM')),
                ('md', models.FloatField(default=0, verbose_name='MD')),
                ('door_closer', models.FloatField(default=0, verbose_name='Доводчик')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
    ]
