# Generated by Django 3.2.11 on 2022-10-23 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSystem', '0007_auto_20221021_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'ordering': ['-holder'], 'verbose_name': 'Баланс', 'verbose_name_plural': 'Баланс'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['-owner'], 'verbose_name': 'Склад', 'verbose_name_plural': 'Склад'},
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='total',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='applications',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 3, 46, 43, 649524)),
        ),
        migrations.AlterField(
            model_name='applications',
            name='published',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 10, 23, 3, 46, 43, 649524), verbose_name='Дата подачи заявки'),
        ),
    ]
