# Generated by Django 3.2.11 on 2022-10-23 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSystem', '0008_auto_20221023_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='counted_eq',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applications',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 14, 58, 11, 236409)),
        ),
        migrations.AlterField(
            model_name='applications',
            name='published',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 10, 23, 14, 58, 11, 236409), verbose_name='Дата подачи заявки'),
        ),
    ]
